### ISSUE TITLE
Missing vcfuniq and vcfstreamsort from vcflib, breaks parallel

### ISSUE THREAD

**Issue by dbgoodman** [freebayes/freebayes#130]
When compiling, `vcfuniq` and `vcfstreamsort` are missing from `vcflib/bin`. These two binaries are needed to use the `freebayes-parallel` feature. This is due to the older linked version of `vcflib`. Workaround is to clone and compile `vcflib` separately and copy the bins back over.

**Comment by tseemann** [comment]
@dbgoodman - I think the issue is that freebayes used vcflib as a sub-module, and only compiles the library, and not all the executables, so it can link against it.   

I have to go into the vcflib/ sub-folder and type "make" to build them, and copy *uniq and *streamsort.

It would be good if freebayes makefile could ensure those two binaries are made and include them in the "make install" target.

It would also be could if the install target could be a makefile variable eg. INSTALLPREFIX=/usr/local so I could override it with my own choice. This would also facilitate a freebayes recipe in Homebrew.

**Comment by colindaven** [comment]
Thanks @tseemann , your hint solved the freebayes-parallel vcflib issue.

**Comment by stephenturner** [comment]
i'm using freebayes and vcflib installed via bioconda, and the `../vcflib/bin/vcfstreamsort` and `../vcflib/scripts/vcffirstheader` are causing problems for me too. if the binaries from vcflib are in your path, i activate the conda environment containing freebayes-parallel, and modify the script to no longer give it a path.

```sh
sed -i 's/\.\.\/vcflib\/.*\///g' $(which freebayes-parallel)
```

this strips out the `../vcflib/(bin|scripts)/` and just calls vcfstreamsort and vcffirstheader from your PATH.

**Comment by crazyhottommy** [comment]
Thanks...I had the same problem and saw this.
