### ISSUE TITLE
combined variant call run.. out puts only one sample 

### ISSUE THREAD

**Issue by gpcr** [freebayes/freebayes#187]
When running multiple samples together i get out put from only one sample?
I checked RG tags and SM ids they are fine

freeBayes v0.9.21-19-gc003c1e

for example:  ##commandline="freebayes -f speedseq/genomes/human_g1k_v37.fasta --region MT:473..907 --min-repeat-entropy 1 705-RLD.realign.bam 704-RLD.realign.bam 706-RLD.realign.bam 707-RLD.realign.bam 708-RLD.realign.bam"
# CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  705-RLD

If I change the order of the bam files,  I get output from the first one only 
# CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  707-RLD

**Comment by luowen711** [comment]
I also had similar problems recently. It turned out that my bam files contain duplicate RG ids.
Each of our bam file contains a bunch of different RG id although RG sm are all unique. Some RG ids are duplicate with other bam file RG ids. I had to change all RG ids to a unique one per bam file so that freebayes would recognize them as different bam files. 
Not sure if that's your case too.

**Comment by ekg** [comment]
I would first check this. If you merge the bam files together would you
still be able to determine which read comes from which sample?

**Comment by danielnavarrogomez** [comment]
Hello,

I had same problem, finally, after comparing bam headers I realized that even having different sample names, they had same ID, I just changed it in one of the samples (following https://www.biostars.org/p/46104/) and now it works as a charm!

**Comment by sambrightman** [comment]
Freebayes sort of fails silently in this situation when it should not. AlleleParser.cpp has an explicit check and error message/exit call for it. However, the combined header text is ultimately obtained from SamReadGroupDictionary of bamtools, which silently discard duplicates. It looks like the header text should instead be constructed from the concatenation of the individual BAM's header texts, so that this information is not lost before checks are made.

**Comment by ekg** [comment]
We are moving to SeqLib, so maybe we can focus our efforts on a fix there?

**Comment by sambrightman** [comment]
#319 allows the existing check to trigger correctly for non-stdin cases.
