### ISSUE TITLE
Memory issues with 14 000 WGS samples

### ISSUE THREAD

**Issue by mfz** [freebayes/freebayes#222]
Hi everyone!

We are trying to call 14 000 WGS samples with an average depth of around 30, but are always running into memory problems.

We are running 2 processes on 64 Gb RAM, where each process receives a 5 kbp region to process, and set option --use-best-n-alleles=4.

Either SLURM kills the process due to excessive memory usage,
or freebayes exits with exit code 137 and simply prints 'Killed'.

The version of freebayes we are running is v1.0.0-19-gefe685d-dirty (previous versions showed the same behaviour).

Any advice on parameter tuning etc. would be appreciated.

Best regards,
Florian

**Comment by ekg** [comment]
Hi @mfz.

Sorry for the delay in getting back to you.

It turns out there was a memory leak when not using --gvcf recently that should have caused exactly this behavior. I just fixed it a few days ago. Would you please test again and let me know? It should be very straightforward to call on 14k samples.

**Comment by mfz** [comment]
Hi Erik,

I did the testing using v1.0.1-1-g683b3cc with --use-best-nalleles 3, using a chunk size of 5000 bp and 16 Gb of memory, but freebayes keeps exiting with exit code 137.
Florian

**Comment by ekg** [comment]
16G is probably not enough. Do you have a system where you could get a
sense for how much memory it needs? It might be >50G.

**Comment by mfz** [comment]
I am currently trying with smaller data sets to see how memory usage scales. 
For 3000 samples with --use-best-n-alleles=3 and chunk size of 5000 bp freebayes needs 10Gb. 

We do have systems with > 50Gb and I'll try to run there. 
It's just a shame to be able to use ony 2 of the 24 cores of a 128 Gb machine ...

**Comment by mfz** [comment]
Hi Erik,

success! For 14 000 samples with --use-best-n-alleles=3 and chunk size of 5000 bp freebayes needs around 30Gb and around 18 hours running time. Which means the whole genome would take us about 10.8 mio CPU hours. The high memory requirement allows us only to use 3-4 CPUs of a 24 CPU, 128 Gb machine though.

Does the algorithm allow for the possibility of threading such that more of the CPUs could be used? Or is there any other way one could reduce the memory requirement? 

Florian

**Comment by ekg** [comment]
Hi Florian,

Great! I am interested in implementing multithreading internally in such a
way as to speed up this use case (high-memory, many samples). There are
some heavily-used loops that could be sped up, but it will take some time
to implement.

My preferred way, using openmp compiler directives, will also be likely to
break compilation on OSX as their clang compile does not support -fopenmp
by default. @dillonl is looking into setting up cmake for vg, and if he
succeeds will produce a recipe to get around this by building gcc or clang
with openmp support when it's necessary.

So it looks like it uses ~2G/1k samples. Depending on where the data is
being used there could be a few big improvements in memory usage that would
get us several X lower there. I haven't optimized the memory usage of
freebayes in some time, and I suspect there are some boneheaded things that
could be improved.

Let me know how it goes, and stay tuned for updates that could help you
iterate this faster.

Erik

**Comment by stuartmichelle** [comment]
Hi, 

I'm having similar problems with freebayes and just want to make sure I understand the numbers above. Are they saying they are running 14,000 samples at 30x coverage of a contig length of 5000bp?  I would love to know how a data set that size can get away with only using 30gb of memory.

We have 1,919 samples at 20x or lower coverage and contig lengths of 211bp.  We have broken our mapped.bed file into 1000 intervals and each interval takes 70G of memory and about 100 minutes to run.  I can only run 3 at a time on my system (~250G memory).  We are using -n 4.  It did not appear to be using more memory at -n 6 or -n 10.  

I am in the process of trying to figure out how to run this on a cluster, using multiple nodes but with only a limited number of cores on each node so that memory isn't over taxed. 

Our current command line is:
ls mapped.*.bed | sed 's/mapped.//g' | sed 's/.bed//g' | shuf | parallel -j 3 --no-notice --delay 1 freebayes -L bamlist.list -t mapped.{}.bed -v raw.{}.vcf -f reference.fasta -m 5 -q 5 -E 3 --min-repeat-entropy 1 -V --populations popmap -n 4

where, as mentioned above, our mapped.bed file has been broken into 1000 pieces and each piece is fed in one at a time.

Any advice you can offer would be greatly appreciated!
Michelle

**Comment by ekg** [comment]
A long time ago I tested 30k samples at 80x depth for an exon sized region
and memory peaked at 30GB. But, this has been a while.

More recently, the thousand genomes project had 2500 samples at 7x depth
and the maximum memory usage for jobs was several GB.

So I am somewhat shocked that things have gotten so much worse and I would
like to figure out what's happening.

Is this on the current HEAD of the repository?

I do not have data available to test this. Is there any way we could share
a contig that causes the problem?

**Comment by stuartmichelle** [comment]
Hi Erik,

Thank you for the fast response.

Our data set is 1919 samples that have undergone ddRADSeq to sequence fragments that are ~211bp in length.  We have a bam file for each of those samples that range in size from 500kb to 500MB.  We use a mapped.bed file to point to each of the contigs in our data set and we have broken that mapped.bed file up into 1000 pieces in order to run the job in intervals.  From what I can understand, every interval of freebayes searches through all 1919 bam files, loading all of them into memory at 70G per interval.

It is hard to re-create the memory problem without the full dataset, which we could put up on an http server for you to access if you have interest.  

We are using versions version:  v1.0.2, v1.0.2-29-g41c1313, v1.0.2-33-gdbb6160-dirty on three different systems, the last 2 are clusters that we are still trying to figure out the best command line for.

Any advice you can offer is greatly appreciated and please let me know if you want me to put our dataset up on the http server.

Sincerely,
Michelle

**Comment by ekg** [comment]
I wonder if the size of the indexes is what's causing the high memory usage.

It's possible to pipe data into freebayes using an external problem (such
as samtools) to read regions from the BAM files. It tends to be more memory
efficient than BamTools, which is what freebayes is based around.

I'd very much like to rewrite freebayes to use htslib (which underlies
samtools).

If it isn't the indexes, then maybe we could reproduce this with a single
contig. This would mean subsetting the entire dataset to a single contig,
generating one file per sample, and then checking if this causes the same
problem.

**Comment by stuartmichelle** [comment]
Yes, our cat-RRG.bam file is 93G.  

I will work on generating a dataset of 1 contig and let you know how it goes.

Thanks!

**Comment by ekg** [comment]
Wow! The memory usage is nearly the same as the entire BAM file!

Have you tried running on just one merged file? As long as the read groups
separate the samples, this should be identical in result, and the index
structures will be much smaller.

**Comment by stuartmichelle** [comment]
When you say one merged file do you mean like:

freebayes -L bamlist.list -t mapped.bed -v raw.vcf -f reference.fasta -m 5 -q 5 -E 3 --min-repeat-entropy  1 -V --populations popmap -n 4


Instead of:

ls mapped.*.bed | sed 's/mapped.//g' | sed 's/.bed//g' | shuf | parallel  -j 3 --no-notice --delay 1 freebayes -L bamlist.list -t  mapped.{}.bed -v raw.{}.vcf -f reference.fasta -m 5 -q 5 -E 3 --min-repeat-entropy 1 -V --populations popmap -n 4


I haven’t tried that because we pulled this line of code out of dDocent to run freebayes on its own because of the memory issue but in about an hour one of the intervals will be done and I can try it…

-M

**Comment by ekg** [comment]
Rather, file, as there will then only be one index file.

**Comment by stuartmichelle** [comment]
Sorry, like a nub I’m learning as I go along and not quite sure which file you’re referring to…the inputs that I see for freebayes are our bamlist.list, which seems like an index, the mapped.bed, which also seems like an index, and our reference.fasta alignment.  My guess is that the bamlist tells freebayes where the data for the contigs in mapped.bed are hiding.  We do have a cat-RRG.bam file, which I think might be a merged file…

It is generated with this code:
bamtools merge -list bamlist.list | samtools rmdup - cat-RRG.bam &>/dev/null
samtools index cat-RRG.bam

Are you saying we could use the cat-RRG.bam file instead of -L bamlist.list?

Thanks for your patience on this learning curve...

**Comment by ekg** [comment]
@stuartmichelle sorry, by "index" I mean the file that maps from reference positions to offsets in the BAM file.

The problem with using the bamlist of many files may be that there are many indexes which are large, and require a lot of memory in BamTools to load and work with. By using just the cat-RRG.bam, we might get BamTools to use less memory at runtime, if this is actually what's going on.

So just run freebayes on the cat-RRG.bam without the bam list. You can replace `-L bamlist...` with `-b cat-RRG.bam`.

**Comment by stuartmichelle** [comment]
Thanks!  I’m running a script to create the single contig files and also waiting for the currently running freebayes intervals to stop before trying the cat-RRG.bam line.  I will let you know how it goes…

**Comment by stuartmichelle** [comment]
Holy smokes!  Running the cat-RRG.bam option is using only 4G of memory!!!  This is like a christmas miracle!  Thank you so much.  

It is kind of unclear based on the options descriptions exactly what the difference is here…instead of analyzing all of the bam files, it is analyzing one merged bam file, is that correct?  

 -b --bam FILE   Add FILE to the set of BAM files to be analyzed.

   -L --bam-list FILE
                   A file containing a list of BAM files to be analyzed.

**Comment by ekg** [comment]
That's right. It is exactly the same data but organized differently in
files. The memory difference comes from differences in the memory required
to load one file index vs thousands. So we are lucky because it looks like
the problem is in BamTools and not somewhere in freebayes!

**Comment by stuartmichelle** [comment]
Thanks again for such a fast response and quick solution!  And good job with freebayes, I don’t know what we would do without it.

Cheers and virtual beers!
Michelle

**Comment by ekg** [comment]
@mfz have you considered merging your files by target region using bamtools or samtools, then running calling on only one BAM file / index pair? This looks like it might greatly reduce memory usage. Here we're seeing 15x reduction for 1400 samples. I would love to know if it helps. You can also merge with samtools and stream into freebayes directly without writing a temporary file.

**Comment by jpuritz** [comment]
Hey all,

@stuartmichelle For dDocent, it's not quite equivalent to run the cat-RRG.bam file.  This file contains only unique mappings, and does not have all the reads necessary for genotyping.  If you want to run it the way @ekg is suggesting, you need to run this code instead:

```bamtools merge -list bamlist.list -out cat-RRG.bam &>/dev/null```

@ekg I'm starting to have more and more users run into this problem.  Perhaps, I need to rethink the way I am implementing gnu-parallel.  For RADseq data, we often have 10k-50k reference contigs, all usually under 1kb.  Right now, I use bedtools to generate a bed file with coverage and then split the intervals into a set of 1000 with approximately equal coverage.  Then I feed those intervals into FreeBayes.  Should I consider making a merged BAM file for each interval instead?

**Comment by ekg** [comment]
I think the merged interval would make a lot of sense! If you have a chance
to try it please let us know if it improves things memory wise.

**Comment by stuartmichelle** [comment]
Hi Erik,

Back in July we had this discussion about memory issues and using the -b option to refer to a merged cat-RRG.bam file fixed it. It worked back in July but when I tried to run this again, adding 192 samples to the mix, I get the error:

ERROR(freebayes): Could not open input BAM file: 15
[E::hts_open_format] fail to open file '15'

Searching the web looks like maybe I need to use bamaddrg but I’m not sure *how* to use it in this case. 

Normally I use this line of code to call up freebayes:

ls mapped.*.bed | sed 's/mapped.//g' | sed 's/.bed//g' | shuf | parallel --memfree 50G --no-notice \
--delay 1 freebayes -b cat-RRG.bam -t mapped.{}.bed -v raw.{}.vcf -f reference.fasta \
-m 5 -q 5 -E 3 --min-repeat-entropy 1 -V --populations popmap -n 4 -j 15 &

We are running the latest commit of freebayes and samtools 1.31, bedtools 2.23.0.

Thanks!
Michelle

**Comment by claudiuskerth** [comment]
Hi Michelle,

did you want to run 15 freebayes jobs in parallel? Then move `-j 15` in front of `freebayes` in the command you show above. Otherwise the `-j --use-mapping-quality` option of freebayes doesn't take an argument, as far as I know.

claudius
