### ISSUE TITLE
FORMAT/GQ field has incorrect type

### ISSUE THREAD

**Issue by holtgrewe** [freebayes/freebayes#244]
By the VCF 4.1 and 4.2 specifications, the `FORMAT/GQ` field should be of type `Integer` but it is of type `Float` in Freebayes. This creates problems when trying to merge two VCF files using bcftools.

**Comment by ekg** [comment]
But the GQs are listed as floats? Should we reduce their precision to make
them integers?

**Comment by holtgrewe** [comment]
I guess this is something to take to the VCF standard authors. GPs is floats, PL and GQ are integers.

**Comment by ekg** [comment]
OK I wasn't aware that the difference had been established. I haven't been
involved in the VCF discussion for some time. It seems silly to have QUAL
be a float and GQ be an integer no?

I have been planning to move to PL but now I think that isn't a good idea.

**Comment by holtgrewe** [comment]
I think that standardization brings in a lot of value.

What do you think about adding a flag that enables VCF4.2 standardized types in Freebayes? I could create a PR. Otherwise, I would have to write a post filter for this....

**Comment by ekg** [comment]
A pull request would be great!

Standardization is essential. I am frustrated here because the standard
forces a loss of precision without any justification.

I have made a comment, but it is probably faster to fix it here if it is
important to your analysis.

https://github.com/samtools/hts-specs/issues/129

**Comment by holtgrewe** [comment]
OK, here is my PR
