### ISSUE TITLE
Output FORMAT field AD "Allelic depths" option

### ISSUE THREAD

**Issue by henrikstranneheim** [freebayes/freebayes#270]
Would it be possible to enable an output option writting the AD field as in samtools and GATK:
## FORMAT=<ID=AD,Number=R,Type=Integer,Description="Allelic depths">

I guess this would be the combination of:

**Comment by lczech** [comment]
Hi there, 

is this option still in discussion? Would be nice to have, as this is needed by some workflows, e.g., https://github.com/snakemake-workflows/dna-seq-gatk-variant-calling
(if ported to freebayes instead of GATK, which I just happened to try doing...)

If abandoned, please close this issue, and I'll use some other tool to create the AD annotation instead.

Thanks
Lucas

**Comment by lczech** [comment]
Hm, I'll reopen. Still would be a useful option to have ;-)
