### ISSUE TITLE
FreeBayes Parallel on 3000 samples

### ISSUE THREAD

**Issue by snashraf** [freebayes/freebayes#277]
Hello All,

I was trying to run FreeBayes parallel over 3000 samples. while I am giving 3000 samples but VCF files is only showing 500 Samples.  What could be possible reason for this ? What will be the best practices for such cases?

Thanks
Najeeb

**Comment by ekg** [comment]
It is almost certainly a mismatch between the read groups and sample names. I would guess you only have 500 unique sample names in your input BAM headers. Or, maybe there are only 500 unique read groups. Unfortunately this is out of scope for what freebayes can understand so it simply does what is written in the header. 

You can fix this with bamaddrg or other tools (Picard has a function for this, but I can't remember the name).

**Comment by snashraf** [comment]
When I was trying to run Freebayes-parallel on 3000 samples and  am getting below error.

## 
parallel: Error: Command line too long (271412 >= 131071) at number 0: 1:0-100000...
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr
/gpfs/software/genomics/freebayes/scripts/freebayes-parallel: line 40: 22790 Exit 255                ( cat "$regionsfile" | parallel -k -j "$ncpus" "${command[@]}" --region {} )
     22791 Done                    | vcffirstheader
     22793 Aborted                 (core dumped) | vcfstreamsort -w 1000
     22795 Aborted                 (core dumped) | vcfuniq
##

How to proceed on this ?

Thanks
Najeeb

**Comment by lczech** [comment]
Hey there!

The issue was unfortunately closed by the bot, but without a solution. I am too running into this, incidentally also on ~3k samples. With freebayes 1.3.9, I am getting:

```
Writing to /tmp/bcftools.sB2dAO
parallel: Error: Command line too long (300443 >= 131049) at input 0: GWHBQCW00000001:34000000-34003277
[E::bcf_hdr_read] Input is not detected as bcf or vcf format
Could not read VCF/BCF headers from -
Cleaning
Failed to read from standard input: unknown file type
```

I guess one solution is to break the calling into smaller portions (subsets of the samples). That would not benefit as much from the joint calling then, but I guess at those scales, that would not matter much?! Still, it would require quite a bit more instrumentation in my workflow to break samples apart and merge later - so if there is a cleaner, straightforward solution, that would be better. But I guess except for trying to extend command line length limits (which I probably cannot do on our cluster), there is not really any other way, is there?

Happy to hear any suggestions :-)

Cheers and so long
Lucas
