### ISSUE TITLE
std::bad_alloc error

### ISSUE THREAD

**Issue by jwickes** [freebayes/freebayes#315]
Hi,
I've been trying to run freebayes-parallel across many small regions (10000+) though I've been consistently getting this error: 

```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Error: signal 11:
freebayes[0x4af735]
/lib/x86_64-linux-gnu/libc.so.6(+0x36150)[0x2b41156da150]
freebayes[0x428b98]
freebayes[0x425d97]
freebayes[0x4473a1]
freebayes[0x448069]
freebayes[0x45756e]
freebayes[0x4587a4]
freebayes[0x458fa9]
freebayes[0x409246]
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

```

I'm running the analysis for 1281 bam files (~3tb) on a server using 30 cpus and 300gb of RAM. 

The command I'm using to run it is 
`freebayes-parallel ref.fa.selected.regions 30 -f ref.fa -L list_of_1281_sorted_bams>output.vcf 2>output.err`

Any help would be greatly appreciated! Thanks

**Comment by tseemann** [comment]
When you submit this to your cluster, how much RAM do you request? 
Exactly 300 GB on  single node?
That is ~250 MB per BAM file, but i'm not sure of the overhead within freebayes.

**Comment by jwickes** [comment]
My bad, it's running on a single server and not a cluster, still 30 cpus and 300gb (exactly) of RAM.

**Comment by jwalabroad** [comment]
I have recently made a new fork of freebayes that potentially has less memory overhead for these sorts of operations. It uses [SeqLib](https://github.com/jwalabroad/SeqLib) instead of [BamTools](https://github.com/pezmaster31/bamtools), which seems to use less memory. It works on my test cases of joint calling, but I haven't tried it with the ``freebayes-parallel`` script.

You may find it useful, and it would be helpful to me to see if it worked or if anything came up.

https://github.com/jwalabroad/freebayes

**Comment by ekg** [comment]
@jwalabroad has a pull request stuck in review. We're looking to merge it in as soon as possible!
