### ISSUE TITLE
calling against ambiguous nucleotides in the reference

### ISSUE THREAD

**Issue by LCrossman** [freebayes/freebayes#320]
Hello,
I have not been able to find the answer to this:
I have a consensus sequence which contains N in some positions.
Those positions are variant positions in some cases which is why they are ambigous in the consensus, but I am not able to get variants back from freebayes from where the reference fasta file has an N.
Is this possible?  I mapped the reads with bwa and created the bam with samtools 0.1.19 or samtools 0.1.18.
I would like to see called as a SNP any nucleotides that map to the reference N, thus:
seqname    POS   ID   REF   ALT  QUAL ...
seqname    1        .      N      A      ..

**Comment by ekg** [comment]
We could change freebayes to allow this. However, it's not really designed
to do this.

If you want to solve this quickly, I'd suggest picking a majority allele in
your consensus. Ns cause many problems in alignment and variant calling.
The systems aren't necessarily designed to handle this use case.

This kind of problem is precisely why I am working on
https://github.com/vgteam/vg.

**Comment by LCrossman** [comment]
Hi, thanks, samtools does call against the N but I definitely want to use freebayes so I'll alter consensus which was called by default biopython.
Cheers,
Lisa

**Comment by ekg** [comment]
We should be able to fix this. There is a check which skips N bases in the
reference that can be disabled in a line of code.

Allowing calls against them could introduce a number of issues. For
instance many aligners like to stick alignments randomly against runs of Ns.

Reiterating, it is exactly this kind of issue that we are working on with
vg. In this case you actually have a good model for which bases could be at
the Ns. Why throw that away during the analysis? It is technically possible
to do your analysis with vg. However I won't suggest it now unless you are
excited by the possibility because documentation is lacking due to the
rapid pace of development.
