### ISSUE TITLE
High quality single sample variant gets low quality score when called as pool

### ISSUE THREAD

**Issue by chapmanb** [freebayes/freebayes#332]
Hi all;
We've been working on tracking down an issue with FreeBayes variants being lost due to quality filters in bcbio (https://groups.google.com/d/msg/biovalidation/VW6X9a62noA/6koqo643BgAJ) and Moiz was able to identify a reproducible test case where we see the issue:

```
wget https://s3.amazonaws.com/chapmanb/testcases/freebayes_joint_low_qual.tar.gz
```

When called as a single sample, the variant of interest has a high quality score of 42 and is effectively maintained:

```
single.vcf:16   70176164    .   G   A   42.7576 .   AB=0.225989;ABP=118.442;AC=1;AF=0.5;AN=2;AO=40;CIGAR=1X;DP=177;DPB=177;DPRA=0;EPP=3.87889;EPPR=21.4678;GTI=0;LEN=1;MEANALT=2;MQM=27.65;MQMR=46.8603;NS=1;NUMALT=1;ODDS=9.84525;PAIRED=1;PAIREDR=1;PAO=0;PQA=0;PQR=0;PRO=0;QA=1259;QR=4618;RO=136;RPL=16;RPP=6.48466;RPPR=3.5851;RPR=24;RUN=1;SAF=36;SAP=58.6;SAR=4;SRF=88;SRP=28.557;SRR=48;TYPE=snp;technology.illumina=1  GT:DP:DPR:RO:QR:AO:QA:GL    0/1:177:177,40:136:4618:40:1259:-28.7454,0,-348.333
```

But when called as a trio, it gets assigned an extremely low quality score, resulting in getting mixed in with sequencing noise and lost:

```
joint.vcf:16    70176164    .   G   A   0.0483893   .   AB=0.225989;ABP=118.442;AC=1;AF=0.166667;AN=6;AO=73;CIGAR=1X;DP=750;DPB=750;DPRA=0;EPP=9.70319;EPPR=37.2408;GTI=0;LEN=1;MEANALT=2.33333;MQM=27.5616;MQMR=45.6716;NS=3;NUMALT=1;ODDS=4.49145;PAIRED=1;PAIREDR=0.982169;PAO=0;PQA=0;PQR=0;PRO=0;QA=2289;QR=22738;RO=673;RPL=30;RPP=8.03741;RPPR=23.1472;RPR=43;RUN=1;SAF=66;SAP=106.557;SAR=7;SRF=440;SRP=141.265;SRR=233;TYPE=snp;technology.illumina=1  GT:DP:DPR:RO:QR:AO:QA:GL    0/1:177:177,40:136:4618:40:1259:-28.7454,0,-348.333 0/0:291:291,22:267:8993:22:651:0,-49.7667,-727.529  0/0:282:282,11:270:9127:11:379:0,-57.7146,-738.162
```

Thanks for any tips on explaining why we see this problem and ways to avoid it.

**Comment by chapmanb** [comment]
To follow up, Moiz Bootwalla performed a brilliant analysis of the impact of this on exon calling:

https://groups.google.com/d/msg/biovalidation/VW6X9a62noA/zaNxzebyAgAJ

It was rare, with a median of 20 variants per exome, but prevalent enough to still be worth following up on. We can generate additional test sets if the original one above doesn't provide enough to track down the underlying issue.

**Comment by ekg** [comment]
I'm going to guess the problem is related to the allele balance:

`AB=0.225989`

That's pretty extreme for 40 observations!

The reason it comes up with the set of samples is that the Bayesian model has a term which is meant to approximate the probability that the locus is "sequenceable". It uses allele balance among other things to derive this estimate, an the estimate would become progressively more extreme as we include more samples with a similar level of allele balance.

**Comment by chapmanb** [comment]
Erik -- Thanks for the idea, that is very useful. If these are validating via other methods, is it possible to adjust the quality score calculation to not take allele balance into account as strongly? I'm happy to play with this and validations to see how it affects at a bigger scale.

@mbootwalla do your other examples of this issue show similar allele balance issues? Does that explain what you've been seeing?

**Comment by mbootwalla** [comment]
Thank you Erik and Brad for the information. @chapmanb I'll check my vcfs and see if the allele balance is the issue with the other variants and report back.

**Comment by ekg** [comment]
Yes, this can be disabled with --allele-balance-priors-off

**Comment by ekg** [comment]
I'll be super interested if that resolves the problem here without diminishing performance.

An allele balance like that would suggest a CNV.

The right way to deal with this is not to filter it out. We're interested in genome inference, so we should model what's going on as accurately as possible given the data.

With good candidate CNV calls it would be trivial to call these regions as polyploid with the copy number given by the CNV genotype. This is already trivial to set up in freebayes because each individual in freebayes can have a different copy number for each region of the genome (using `--cnv-map`).

Even approximately good calls would be enough, as the posterior probability of the polyploid model will be higher when the copy number state is the true one. If the CNV caller suggests M or N ploidy, we could test out the M-ploid and N-ploid states, then ask what our average call quality was for some set of candidate SNPs. However, we might want to "regularize" our model by penalizing very high copy numbers, or else we'll tend to prefer those as they're more permissive to errors.

I don't know if anyone has ever tried this. I would love to, but it has never been a clear win due to the effects of really short reads, and now I wonder if the sun is setting on the need for this kind of inference game. Long reads are getting cheaper very quickly, and they can decisively resolve similar problems.
