### ISSUE TITLE
Issues building on OSX?

### ISSUE THREAD

**Issue by kyleabeauchamp** [freebayes/freebayes#334]
Is anyone else still having issues with their OSX builds after the SeqLib update?  I was trying to update the Bioconda build (https://github.com/bioconda/bioconda-recipes/pull/2815/files), but I keep seeing OSX failures (https://travis-ci.org/bioconda/bioconda-recipes/jobs/173537495#L1400) due to the tr1/C++11 issues that were previously discussed.  

AFAIK, I think the issue is that CXXFLAGS are not being propagated to the SeqLib build when I run `make` on freebayes.  CPPFLAGS do seem to get propagated, but it's not appropriate to set c++11 mode via CPPFLAGS because that can cause the HTSLib build to die, as HTSLib is not C++.

**Comment by walaj** [comment]
It does look like make flags are not being passed to SeqLib in the freebayes Makefile. We should probably pass them along, either at the configure call for SeqLib in the freebayes Makefile, or with an ```export CXXFLAGS``` at the top of the freebayes Makefile. Would this address the issue?

Otherwise, I think you should be able to first build SeqLib explicitly (and pass flags), and then build Freebayes. Not the ideal solution, but perhaps may be a sufficient workaround until this is patched. Open to suggestions on best approach for this.

**Comment by kyleabeauchamp** [comment]
I don't have a strong opinion on the best way to pass flags through a makefile, I'm sure any number of approaches would be fine.

**Comment by walaj** [comment]
I updated a [fork](https://github.com/walaj/freebayes) of freebayes which now passes CXXFLAGS etc to sub-shells like SeqLib ```make```. Can you try this out and see if it works for you? For instance, on OSX I am able to now pass ```CXXFLAGS=-std=c++11``` to SeqLib. It also separates out the BamTools version into a separate Makefile, since the default in freebayes is to not use this library now.

On my build however, I don't need any additional flags to ```make``` for an OSX build, but this updated should now at least give users an option without having to do two separate calls to ```make```

**Comment by kyleabeauchamp** [comment]
OK, I had to add a patch file to redefine `CXX=g++ $FXXFLAGS` in the FreeBayes/src makefile. It turns out the remaining problem was in the freebayes compilation, which compiles both c++ and c files to build with the same set of compiler flags (`CFLAGS`).  

With that change, I was able to get the bioconda build to work:

https://github.com/bioconda/bioconda-recipes/pull/2815

I'm not going to merge my bioconda PR until things are sorted out longer term.

**Comment by kyleabeauchamp** [comment]
Any thoughts on whether we want to open a PR to master with the changes from your fork?  Do you see any reason not to?  

cc @chapmanb

**Comment by chapmanb** [comment]
+1 from me, it would be great to have this fix for clean OSX compilation in the main FreeBayes master. Thanks for all the work integrating SeqLib, I'm excited to start using 1.1.0.

**Comment by walaj** [comment]
Thanks for following up on this, I don't see a reason not to merge them. Following @kyleabeauchamp suggestion, I separated CFLAGS and CXXFLAGS to follow C / C++ conventions. I also separated out the Bamtools compilation into a separate Makefile.bamtools, so that CMake and building Bamtools won't be necessary with the default SeqLib build. Will issue PR now, and hopefully you and @chapmanb can let me know if any issues with it.
