### ISSUE TITLE
REF allele is missing  or . (dot) instead of A,C,G,T,N in a GVCF Block

### ISSUE THREAD

**Issue by sowmiu** [freebayes/freebayes#367]
GVCF Block output on NA12878 sample generated using gvcf_chunk=100000, has reference allele missing (dot in place of allowed A,C,G,T,N).  There are multiple non-variant blocks in the GVCF file where reference allele is missing.

Example - REF is . and ALT is <*>.  I would expect the REF allele to denote the  reference at position 140509076, even if it is N.

chr10   140509076       .       .       <*>     0       .       DP=0;END=141213431;MIN_DP=0     GQ:DP:MIN_DP:QR:QA      177542:0:0:177542:-0

Thanks and Best

**Comment by finswimmer** [comment]
Can confirm this. 

According to the [vcf specs](http://samtools.github.io/hts-specs/VCFv4.3.pdf) REF must be one of A, C, G, T, N.

For the moment as a workaround one can use `bcftools +fill-from-fasta` to fix it:

```
bcftools +fill-from-fasta input.gvcf -- -c REF -f reference.fa > output.gvcf
```

**Comment by ekg** [comment]
Ok this should be simple enough to fix.

I'm not sure I agree with the spec on this. Why do we report only the start
position character when there are thousands of bp of sequence in the
reference allele?

**Comment by finswimmer** [comment]
Thanks for looking at this Erik!

> Why do we report only the start
position character when there are thousands of bp of sequence in the
reference allele?

The spec have this is answer to it in 5.5:

> The convention adopted here is to represent reference evidence as
likelihoods against an unknown alternate allele. Think of this as the likelihood for reference as compared to any
other possible alternate allele (both SNP, indel, or otherwise). A symbolic alternate allele <*> is used to represent
this unspecified alternate allele.
