### ISSUE TITLE
freebayes lost a truth indel

### ISSUE THREAD

**Issue by sheepting** [freebayes/freebayes#433]
I use the mutect2 and freebayes to call variants.i found freebayes lost a truth indel .
![360 20171122172638867](https://user-images.githubusercontent.com/23272101/33119687-b89143d2-cfaa-11e7-82a6-3d1c27d29e75.png)
the freebayes jumps over this area.
![360 20171122173137757](https://user-images.githubusercontent.com/23272101/33119800-12ae8d0c-cfab-11e7-8fb0-55b447a244d4.png)
I use the parameter freebayes --min-mapping-quality 0 --min-base-quality 20 --haplotype-length 0  --report-all-haplotype-alleles
do I use the false parameter to call variants?

**Comment by mmoisse** [comment]
I had a similar issue and it is also related to #288 
According to me it has something to do with the way freebayes asses the quality of a indel.

>   -H --harmonic-indel-quality
>                   Use a weighted sum of base qualities around an indel, scaled by the
>                   distance from the indel.  By default use a minimum BQ in flanking sequence.


I found two ways to solve it:

1. Set min base quality to 0 (--min-base-quality 20)
2. Add --harmonic-indel-quality

I hope it helps

**Comment by ekg** [comment]
Thank you @mmoisse, this is very interesting. Do you find the mapping quality is 0 for the reads overlapping the indel?

**Comment by sheepting** [comment]
Thank you @mmoisse .I adopt your advice, but it did not work.Do you add  other parameters ?

**Comment by mmoisse** [comment]
I believe I now understand why @sheepting is missing the indel. It is because there are overlapping indels namely:

    chr16 67645338 . CAAAAAAAC CAAAAAAC
and 

    chr16 67645346 . CAAAG CG

I have the impression that if the last base of an indel overlaps with the first base of the following indel, the second indel does not get called. Additionally the read depth at the first indel is too low (missing the reads of the second indel). See the test case below, where I created 200 reads with some indels in the reads:

[missedIndel.zip](https://github.com/ekg/freebayes/files/1963758/missedIndel.zip)

![missed indel igv_snapshot](https://user-images.githubusercontent.com/7941646/39472896-5f993b7a-4d4c-11e8-8ea7-c6aa24d2ee0a.png)

In the example where the indels are sequential you miss the second indel and the coverage is only 100 instead of the expected 200.

    freebayes -f ref.fa --min-repeat-entropy 1 missedIndel.sequential.bam

    #CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  Test
    4       191     .       TATGA   TA      2645.2  .       AB=0;ABP=0;AC=2;AF=1;AN=2;AO=100;CIGAR=1M3D1M;DP=100;DPB=40;DPRA=0;EPP=5.18177;EPPR=0;GTI=0;LEN=3;MEANALT=1;MQM=60;MQMR=0;NS=1;NUMALT=1;ODDS=141.625;PAIRED=0;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=3300;QR=0;RO=0;RPL=100;RPP=220.158;RPPR=0;RPR=0;RUN=1;SAF=55;SAP=5.18177;SAR=45;SRF=0;SRP=0;SRR=0;TYPE=del;technology.Test=1   GT:DP:RO:QR:AO:QA:GL    1/1:100:0:0:100:3300:-297.252,-30.103,0

In the second example the only the first indel is kept and an other random not sequential indel is inserted. Now both indels are found with the expected coverage of 200.

    freebayes -f ref.fa --min-repeat-entropy 1 missedIndel.first.onlybam

    #CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  Test
    4       114     .       TGTATGAAGTACAGTGGAAG    TG      2019.51 .       AB=0.5;ABP=3.0103;AC=1;AF=0.5;AN=2;AO=100;CIGAR=1M18D1M;DP=200;DPB=110;DPRA=0;EPP=7.26639;EPPR=5.18177;GTI=0;LEN=18;MEANALT=1;MQM=60;MQMR=60;NS=1;NUMALT=1;ODDS=465.01;PAIRED=0;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=3300;QR=3300;RO=100;RPL=0;RPP=220.158;RPPR=220.158;RPR=100;RUN=1;SAF=57;SAP=7.26639;SAR=43;SRF=55;SRP=5.18177;SRR=45;TYPE=del;technology.Test=1      GT:DP:RO:QR:AO:QA:GL    0/1:200:100:3300:100:3300:-237.046,0,-237.046
    4       191     .       TATGA   TA      2023.66 .       AB=0.5;ABP=3.0103;AC=1;AF=0.5;AN=2;AO=100;CIGAR=1M3D1M;DP=200;DPB=140;DPRA=0;EPP=5.18177;EPPR=7.26639;GTI=0;LEN=3;MEANALT=1;MQM=60;MQMR=60;NS=1;NUMALT=1;ODDS=465.01;PAIRED=0;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=3300;QR=3300;RO=100;RPL=100;RPP=220.158;RPPR=220.158;RPR=0;RUN=1;SAF=55;SAP=5.18177;SAR=45;SRF=57;SRP=7.26639;SRR=43;TYPE=del;technology.Test=1        GT:DP:RO:QR:AO:QA:GL    0/1:200:100:3300:100:3300:-237.046,0,-237.046

In the third example the only the second indel is kept and an the same random not sequential indel is inserted. Now both indels are found with the expected coverage of 200.

    freebayes -f ref.fa --min-repeat-entropy 1 missedIndel.second.only.bam | grep -v '##'

    #CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  Test
    4       114     .       TGTATGAAGTACAGTGGAAG    TG      2019.51 .       AB=0.5;ABP=3.0103;AC=1;AF=0.5;AN=2;AO=100;CIGAR=1M18D1M;DP=200;DPB=110;DPRA=0;EPP=7.26639;EPPR=7.26639;GTI=0;LEN=18;MEANALT=1;MQM=60;MQMR=60;NS=1;NUMALT=1;ODDS=465.01;PAIRED=0;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=3300;QR=3300;RO=100;RPL=0;RPP=220.158;RPPR=220.158;RPR=100;RUN=1;SAF=57;SAP=7.26639;SAR=43;SRF=57;SRP=7.26639;SRR=43;TYPE=del;technology.Test=1      GT:DP:RO:QR:AO:QA:GL    0/1:200:100:3300:100:3300:-237.046,0,-237.046
    4       194     .       GATCA   GA      2019.51 .       AB=0.5;ABP=3.0103;AC=1;AF=0.5;AN=2;AO=100;CIGAR=1M3D1M;DP=200;DPB=140;DPRA=0;EPP=7.26639;EPPR=7.26639;GTI=0;LEN=3;MEANALT=1;MQM=60;MQMR=60;NS=1;NUMALT=1;ODDS=465.01;PAIRED=0;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=3300;QR=3300;RO=100;RPL=100;RPP=220.158;RPPR=220.158;RPR=0;RUN=1;SAF=57;SAP=7.26639;SAR=43;SRF=57;SRP=7.26639;SRR=43;TYPE=del;technology.Test=1        GT:DP:RO:QR:AO:QA:GL    0/1:200:100:3300:100:3300:-237.046,0,-237.046
