### ISSUE TITLE
freebayes "Segmentation fault" 

### ISSUE THREAD

**Issue by LucysWorld** [freebayes/freebayes#442]
Dear Community,

I want to align some RAD data of a non-model organism to a genome of the same species. 
For that I followed this tutorial so far: https://github.com/ekg/alignment-and-variant-calling-tutorial

When using freebayes I get the following error: "Segmentation fault" (nothing more except these two words, no number and no error code etc. )

I called freebayes as follows:
$ freebayes -f  genome.fasta fastQ-processradtags/Rad-seq.fq.raw.bam >output.vcf

I'm using it on a Debian Server: 
Distributor ID: Debian
Description:    Debian GNU/Linux 9.3 (stretch)
Release:        9.3
Codename:       stretch

Do You have any Idea what I'm missing/ doing wrong here?

Thanks for your help, time and consideration
Lucy

**Comment by mbelmadani** [comment]
That sounds like a compilation issue. Did you run into anything weird (error or failure messages) during installation (`make` then `make install`)?

**Comment by LucysWorld** [comment]
I installed it locally on a server and only used following commands:
# getting freebayes
git clone --recursive git://github.com/ekg/freebayes.git

# go to folder 
cd freebayes && make

Do you think I have to use the make install command (and therefore the Server Admin has to do this?)

Cheers and thanks for your fast feedback!

**Comment by mbelmadani** [comment]
It should be enough to run make, `make install` just copies the content of bin/ to /usr/local/bin/.

What happens when you just run `./freebayes` or `./bin/freebayes`? You should see something like this:

```
$ ./freebayes 
usage: ./freebayes -f [REFERENCE] [OPTIONS] [BAM FILES] >[OUTPUT]

Bayesian haplotype-based polymorphism discovery.

parameters:

   -h --help       For a complete description of options.

citation: Erik Garrison, Gabor Marth
          "Haplotype-based variant detection from short-read sequencing"
          arXiv:1207.3907 (http://arxiv.org/abs/1207.3907)

author:   Erik Garrison <erik.garrison@bc.edu>, Marth Lab, Boston College, 2010-2014
version:  v1.1.0-56-ga180635

```
If the help menu doesn't show up, then there's an issue with compilation. I was also able to run a commmand like yours and a VCF file was being written.

I was going to say to try to run  `make test` from the freebayes directory but I'm noticing a couple of failed test on my end as well, even though freebayes appears to work, so I'm not sure how expected this is.

Maybe try to rebuild and see if it helps, and see if make ends with an error or anything suspicious:
`make clean`
`make`

Otherwise, can you paste the version of g++ and make?
```
$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) 
```

```
$ make -v
GNU Make 3.82
Built for x86_64-redhat-linux-gnu
Copyright (C) 2010  Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by ekg** [comment]
Do you have `bin/freebayes` at the end of compilation?

You don't have to `make install`. That target just copies freebayes and bamleftalign into /usr/local/bin/.  You can add freebayes/bin to you own `$PATH`, or copy it to a directory in your path that you have write access to. On multiuser systems I always add `$HOME/bin` and make that the first entry in my path.

**Comment by ekg** [comment]
I agree. Did you build this from scratch yourself?

**Comment by LucysWorld** [comment]
What do you mean with "Did you build this from scratch yourself" ?

In regards to the compilation issue I posted the requested Calls and the outputs above.

As mentioned above I used the following commands to install the program
_git clone --recursive git://github.com/ekg/freebayes.git
cd freebayes && make_

afterwards I exported the PATH to the $PATH variable and was able to call it from every position. 

When you agree that there is a compilation issue, what could I do differently during installation/compilation?

**Comment by ekg** [comment]
> afterwards I exported the PATH to the $PATH variable and was able to call it from every position.

This makes it seem that there isn't an issue. I'm confused if you are still having a problem.

**Comment by LucysWorld** [comment]
Could it be an issue with the input files?
Although I tried different data sets(input files)  I'm still open for any possible explanation?

**Comment by ekg** [comment]
What happens when you run "make test" in the freebayes directory?

**Comment by LucysWorld** [comment]
when I call "make test" in the freebayes dirctorys it runs sucessfully through all test:

```
All tests successful.
Files=4, Tests=42, 26 wallclock secs ( 0.06 usr  0.01 sys + 23.39 cusr  0.63 csys = 24.09 CPU)
Result: PASS
make[1]: Leaving directory '/path/to/freebayes/test'
```

**Comment by ekg** [comment]
Good, this mean that the freebayes you built is working fine. Now, can you
confirm that when you run this freebayes you get a failure on your data?
Con you verify that the data is correctly formatted by running another
variant caller or using samtools view on the BAM?

**Comment by LucysWorld** [comment]
I can use "samtools view" without problems on the bam file. But the file is 699Mb big. Could that be an issue?

**Comment by ekg** [comment]
The file size is not an issue. You can use any sized file as input to freebayes.

From your freebayes build directory, try running `bin/freebayes -f ref.fa file.bam >out.vcf`.

**Comment by LucysWorld** [comment]
then the error still occurs

/programs/freebayes/bin$ ./freebayes -f ../../../genome.fasta ../../../bams/sample.fq.raw.bam >out.vcf
Segmentation fault

**Comment by ekg** [comment]
Is the input bam sorted? Add --debug and see where it stops.

**Comment by LucysWorld** [comment]
here is the --debug output:

bin$ ./freebayes -f ../../../genome.fasta ../../../sample.fq.raw.bam --debug >out.vcf

loading fasta reference ../../../SNP-project/hirise-dovetail-original.fasta
Opening BAM format alignment input file: ../../../SNP-project/fastQ-processradtags/fastQ-proccessradtags-bams/P1-031.fq.raw.bam ...
done
Number of ref seqs: 2025248
Number of target regions: 0
no sample list file given, reading sample names from bam file
found 1 samples in BAM file
Segmentation fault

**Comment by ekg** [comment]
Is the BAM file sorted? The fact it's called "raw" makes me wonder.

**Comment by akijarl** [comment]
I've been running into an identical issue.
Freebayes appears to be compiled correctly (managed to complete the [tutorial](https://github.com/ekg/alignment-and-variant-calling-tutorial)), yet every time I run one of my exon capture files I get 

`loading fasta reference Tg_ExoCap_orfs.fa
Opening BAM format alignment input file: A01.clean.bam ...
 done
Number of ref seqs: 278057
Number of target regions: 0
no sample list file given, reading sample names from bam file
found 1 samples in BAM file
Segmentation fault: 11`

This Segmentation fault error shows up both locally and when I attempt to run it on my institution's cluster.

The sequence files were trimmed using Trimmomatic, and mapped using bwa with only the trimmed pair files. I've tried adding tags with bamaddrg and then re-did the bwa mapping setting read group and sample id there. Files are sorted, indexed, and PCR duplicates are removed with samtools markdup.

I did try the `make test` command in the freebayes folder and got the following:

`11 warnings and 1 error generated.
make[2]: *** [src/cdflib.o] Error 1
make[1]: *** [../vcflib/bin/vcfuniq] Error 2
make: *** [test] Error 2`

Would really appreciate any insight: if there's a compilation error I don't understand how was I able to run through the test data, or why the same segmentation fault come up on multiple platforms.

**Comment by atfields** [comment]
I have been working with dDocent for several datasets and have not had any issue with freebayes. On one of my more recent datasets though I keep getting this segmentation fault. I have tried freebayes v1.1.0-54-g49413aa and v1.2.0.

Originally when I used this dataset, I was using a genome assembly from masurka and everything was working well. I have some very long contigs (>1Mbp) though and it is likely that loci on opposite ends of this act differently. Scripting wise, I thought it would be easier to break the contigs in the reference rather than rename the contigs in the vcf file, so using bedtools I broke the contigs in my reference, and with bash I added a number to the end of the name of the contig to make them unique and then remapped my samples (with bwa via dDocent).

e.g.
Original contig: >jcf7180004243889_pilon
New contigs: >jcf7180004243889_pilon_1; >jcf7180004243889_pilon_2

# of Original contigs = 154064
# of New contigs = 508393

The mapping went fine. Visually I don't see an issue with the reference file, the bam file or the bed file. I can view the bam file with IGV on the reference file, but when I run freebayes I get a seg. fault.

Running the debug command suggested by @ekg results in:
```
$ ~/programs/freebayes/bin/freebayes --debug -f reference.fasta split.1.bam >out.vcf
loading fasta reference reference.fasta
Opening BAM format alignment input file: split.1.bam ...
 done
Number of ref seqs: 508393
Number of target regions: 0
no sample list file given, reading sample names from bam file
found 32 samples in BAM file
Segmentation fault (core dumped)
```

file sizes:
172M split.1.bam
220M reference.fasta
0        out.vcf

I don't think this is an installation error or a sorting issue since I have run this dataset previously with dDocent and a different reference and it worked. The two things I see are:
1) the number of contigs is much higher, but I have other datasets that have a large number and freebayes doesn't have an issue 
2) the naming of the contig is not quite conventional for me. Usually I only have 1 number in the name, but I have added a second number, but I didn't think this should matter.

I would appreciate any help with parsing this issue out. Thank.

**Comment by jpuritz** [comment]
I’d remove the second > from the reference header and additionally check
for any unmarked or hidden characters in the reference.



-- 
Jon Puritz, PhD

Assistant Professor
Department of Biological Sciences
University of Rhode Island
120 Flagg Road, Kingston, RI 02881

Webpage: MarineEvoEco.com

Email:
jpuritz@gmail.com

Cell:    401-338-8739
Work:  401-874-9020

"The most valuable of all talents is that of never using two words when one
will do.” -Thomas Jefferson


On June 13, 2018 at 10:46:56 AM, atfields (notifications@github.com) wrote:

I have been working with dDocent for several datasets and have not had any
issue with freebayes. On one of my more recent datasets though I keep
getting this segmentation fault. I have tried freebayes v1.1.0-54-g49413aa
and v1.2.0.

Originally when I used this dataset, I was using a genome assembly from
masurka and everything was working well. I have some very long contigs
(>1Mbp) though and it is likely that loci on opposite ends of this act
differently. Scripting wise, I thought it would be easier to break the
contigs in the reference rather than rename the contigs in the vcf file, so
using bedtools I broke the contigs in my reference, and with bash I added a
number to the end of the name of the contig to make them unique and then
remapped my samples (with bwa via dDocent).

e.g.
Original contig: >jcf7180004243889_pilon
New contigs: >jcf7180004243889_pilon_1; >jcf7180004243889_pilon_2
of Original contigs = 154064 of New contigs = 508393

The mapping went fine. Visually I don't see an issue with the reference
file, the bam file or the bed file. I can view the bam file with IGV on the
reference file, but when I run freebayes I get a seg. fault.

Running the debug command suggested by @ekg <https://github.com/ekg>
results in:

$ ~/programs/freebayes/bin/freebayes --debug -f reference.fasta
split.1.bam >out.vcf
loading fasta reference reference.fasta
Opening BAM format alignment input file: split.1.bam ...
 done
Number of ref seqs: 508393
Number of target regions: 0
no sample list file given, reading sample names from bam file
found 32 samples in BAM file
Segmentation fault (core dumped)

file sizes:
172M split.1.bam
220M reference.fasta
0 out.vcf

I don't think this is an installation error or a sorting issue since I have
run this dataset previously with dDocent and a different reference and it
worked. The two things I see are:

   1. the number of contigs is much higher, but I have other datasets that
   have a large number and freebayes doesn't have an issue
   2. the naming of the contig is not quite conventional for me. Usually I
   only have 1 number in the name, but I have added a second number, but I
   didn't think this should matter.

I would appreciate any help with parsing this issue out. Thank.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ekg/freebayes/issues/442#issuecomment-396964213>, or mute
the thread

**Comment by atfields** [comment]
```
"I’d remove the second > from the reference header and additionally check
for any unmarked or hidden characters in the reference." -jpuritz
```
There isn't actually two > in the reference header. That was just an example of how the reference contig name was split. I have not found any hidden characters.

reference file output:
```
>jcf7180004243889_pilon_1
AATTTGTTTACTCGGGTTAGCTCGAATGCTAGCTTTGACAGTTAGCCTTCAGTGTTGCTTTGCTAACGGCCTTCCACCCGGTCGGAACGTACAAATATCTATAACTGCACAGTCATTCCTTGACATACCTTTTTATGATAAGCTTTCTTTGGCGCTCCAGTCCGATAGATTCCTTCATTTTGTCCATAATTAGCTGTTTTAACAAGTTTAAGGGGCTATTGTTTCTCGAAAACACAGACGATATCGTCTGAGCACACCGGAGAGGGCCTCCAAAATGTCTCTCTGGTTTGTAAGGAGCTCGGTGATTGGTCCGTTTCAGAAAACCAGGGGGCTCGATTCATTTAAGGGCGTTGCCTGGCAACACTACTGATAGAAGCTCCAGTCTGTAGAACCACAGCATAGCTGATTACGTAATATGTTTACCAAGATGTTGTTCCATGTTTACCCTGCAATCACTCAAAAAGGCGAGGCTACAACAATATGGTATCATCATATAATTTCTCACAACAATATTTATTTTAAGTAATAACATCATAACAACATAACATAACATATAATATT
>jcf7180004243889_pilon_2
CGGTGAAAGCGGGTCTCCTCAGCAGAGAGCCCCTTGTGAGGAGAATACCCAGCGTCTGTCAGGCCTGCCTGGTGCTCAAACTTCTGTAGATTCTCATGTGTCTGCTCTAAGTGAAGATGGAGATACAGTTGACAGTGGATATAAAATTAGTTAATGTTTTAATATGCTGCCCTATATTGTTGCTCGCTGATACTCTGCACTGAATACTGTTCATCCATATTTGGAAATCAAGGCAGCAGCTATTTAGACAATCAGCGATAACGCTTGCACAATTCTGTCACATGTGGCCTTGTGAAGGAATT
```

**Comment by atfields** [comment]
Hannes,
The message you posted indicates that there were no samples found in the BAM file. Is this right? Could that be a source of your error? I don't know if that should cause a seg fault.

**Comment by hannesbecher** [comment]
> Hannes,
> The message you posted indicates that there were no samples found in the BAM file. Is this right? Could that be a source of your error? I don't know if that should cause a seg fault.

It is true, when mapping I did not assign read groups and so freebayes does not find "samples". But this did not stop freebayes from readily processing a similar file (albeit with fewer contigs).
```
bash-4.2$ ~/git_repos/freebayes/bin/freebayes --debug -f ~/assemblies/Tetraploid/EuphrasiaNBER_Pacbio_Canu.unitigs.fasta /media/Euphrasia_backup/ArcCanuMappings/ArcIll_sorted_dedupped.bam | head
loading fasta reference /localdisk/home/hbecher/assemblies/Tetraploid/EuphrasiaNBER_Pacbio_Canu.unitigs.fasta
Opening BAM format alignment input file: /media/Euphrasia_backup/ArcCanuMappings/ArcIll_sorted_dedupped.bam ...
 done
Number of ref seqs: 28582
Number of target regions: 0
no sample list file given, reading sample names from bam file
found 0 samples in BAM file
##fileformat=VCFv4.2
##fileDate=20181028
##source=freeBayes v1.2.0-2-g29c4002
##reference=/localdisk/home/hbecher/assemblies/Tetraploid/EuphrasiaNBER_Pacbio_Canu.unitigs.fasta
##contig=<ID=tig00000001,length=26900>
##contig=<ID=tig00000002,length=33549>
##contig=<ID=tig00000003,length=39058>
##contig=<ID=tig00000004,length=27392>
##contig=<ID=tig00000005,length=107765>
##contig=<ID=tig00000006,length=341136>
```

**Comment by ekg** [comment]
Would one of you please provide a minimal test case which reproduces the
segfault?

**Comment by webbchen** [comment]
Dear Erik
Found the same issue. A segmentation fault occurring when calling SNPs against a transcriptome (no genome available). Read groups are present, bam files have been sorted and duplicates marked.
Specifying a few or a single contig as a region didn't help. 
Our same installation of freebayes has been working through 315 bams and a genomic reference without complaint.
The command:
$ freebayes -r contig0_c1550_g31432_i1:0-4545 -f /path/to/hedin_transcriptome_v2.fasta -L /path/to/faba_bams.txt --debug --vcf /path/to/all_faba_SNPs1.vcf

yields:
"
Opening output file: /path/to/all_faba_SNPs1.vcf ...
loading fasta reference /path/to/hedin_transcriptome_v2.fasta
Opening 13 BAM format alignment input files
 done
Number of ref seqs: 200293
will process reference sequence contig0_c1550_g31432_i1:0..4545
Number of target regions: 1
no sample list file given, reading sample names from bam file
found 13 samples in BAM file
Segmentation fault
" 
and an empty output file.
Test case:
I replicated the issue with the same ref but my two smallest of bam files, is there a way of transferring ~ 7Gb of files to you in private so you look at it?

Regards,
A. Webb

**Comment by webbchen** [comment]
That'd be good!

**Comment by ianbed** [comment]
Hi, was this issue resolved? I am also experiencing a similar error with v1.2.0-2-g29c4002. I am also calling variants on a large transcriptome assembly:

Error message:
Number of ref seqs: 474313
Number of target regions: 0
no sample list file given, reading sample names from bam file
found 1 samples in BAM file
Segmentation fault

This error also persists if I run with a single target region.

Interestingly (perhaps related?) I am also experiencing an error with the -L option:
[E::hts_open_format] Failed to open file test.sorted.rg.bam
ERROR(freebayes): Could not open input BAM file: test.sorted.rg.bam

Those bam files are sorted, with read groups and work OK using other tools/variant callers.
Thanks for any help on resolving this!

**Comment by bacms2** [comment]
An update on this. Getting the same issue on version v1.2.0-4-gd15209e. Happy to provide a small reproducible case if needed. 
loading fasta reference CassavaPangenomev0.1.fa
Opening BAM format alignment input file: sorted_bam_test ...
 done
Number of ref seqs: 231785
Number of target regions: 0
no sample list file given, reading sample names from bam file
found 25 samples in BAM file
Segmentation fault

**Comment by ekg** [comment]
Yes, I definitely need an example that reproduces this.

**Comment by gagayuan** [comment]
First,  I also encountered this issue when I execute 
`freebayes -f ref.fa aln.bam >var.vcf`
 It shows "Segmentation fault",and I find lots of solutions posted were about "install freebayes", so I choose to use a [docker](https://hub.docker.com/r/ctomlins/freebayes_polish) to avoid "install issue".

Second, In the docker ,I also get "Segmentation fault",when I get into docker's bash and execute
 `**ulimit -s 81920**` to Expand stack space ten times,then  execute `freebayes -f ref.fa aln.bam >var.vcf` Successfully.
This means **stack limit** is the key to solve the "Segmentation fault". I recommend anyone who encounter this problem should try `ulimit -s` though you don't use docker.

At last , via docker I execute 
`docker run -ti --ulimit stack=8277716992:8277716992 -v /media:/media ctomlins/freebayes_polish freebayes -f /media/test.fa /media/test.bam >/media/test.bam.vcf`
successfully run freebayes.

If this can help anyone ,it's my pleasure.

**Comment by ekg** [comment]
That's interesting. Segfaults can be caused by several things. This does
suggest that there may be a problem with recursion running out of control,
and I can investigate possible causes.

**Comment by bacms2** [comment]
I actually managed to sort the problem. There is a limit on the number of reference sequences you can have on your bam file. I am assuming this is probably related to the BAM library using a variable that is too small to store this number but not followed through into it to confirm. But splitting the bam files and the headers manually by chromosome solved the problem

**Comment by ekg** [comment]
What's the limit? Perhaps the problem is that the header is stored on the
stack, and not that the number in the library is small. I'd be surprised if
it were less than 32 bits, which is an awful lot of reference sequences.

**Comment by Grelot** [comment]
I got the same issue of segmentation fault with freebayes version 1.3.1-17-gaa2ace8.
I used freebayes 2 years ago with dDocent and it worked fine on the same data.

I installed my freebayes into a container : https://singularity-hub.org/collections/3319

```
 git clone --recursive https://github.com/ekg/freebayes.git
    cd freebayes
    make
    cd bin
    chmod +x *
    cp -f * /usr/local/bin
    cd ..
    cd ./vcflib/
    make
    chmod +x ./bin/*
    cp -f ./bin/* /usr/local/bin
    cd ../..
```
a command to test
```
singularity exec seaconnect.simg freebayes --debug -f 04-ddocent/mullus/reference.fasta 04-ddocent/mullus/C100_M100i10E2-RG.bam > ou.vcf
```
and the results : (same for all my others .bam files)

```
loading fasta reference 04-ddocent/mullus/reference.fasta
Opening BAM format alignment input file: 04-ddocent/mullus/C100_M100i10E2-RG.bam ...
 done
Number of ref seqs: 361602
Number of target regions: 0
no sample list file given, reading sample names from bam file
found 1 samples in BAM file
Erreur de segmentation

```

**Comment by Grelot** [comment]
reducing the number of scaffolds (ref seqs) solved the problem.

**Comment by SusanaFreitas** [comment]
Hello all,
After using FB for a while without any problems, but recently I am having the same problem described here:

```
loading fasta reference 3_Tms_b3v08.fasta
Opening 46 BAM format alignment input files
 done
Number of ref seqs: 189023
Number of target regions: 0
no sample list file given, reading sample names from bam file
found 46 samples in BAM file
Segmentation fault
```

And the command line:

` freebayes -f 3_Tms_b3v08.fasta --bam-list trim3bam --min-mapping-quality 30 --min-coverage 5 --debug > Tms.trim3.fb.vcf`

I re-sorted the bam files, re-indexed the fasta, increased memory, and tried calling SNPs with only 2 of the bams and still get the same "Segmentation fault"
I ran FB on another dataset (with a different reference genome) and it ran without problems.

Did any of you find a solution (apart from reducing the number of scaffolds in the ref genome)?

Many thanks!!

**Comment by SusanaFreitas** [comment]
I forgot to mention that I am using version 1.2.0 (installed as a model in my server), but I also get the same error if I use the most recent FB version.

It would be great if anyone had some suggestion or could help...
Thanks!

**Comment by atfields** [comment]
Hi SusanaFreitas,

If you are running on linux, have you tried gagayuan's suggestion of changing the ulimit (`ulimit -s 81920`)? I found that if I have a very large number of contigs in my reference fasta file, then increasing this limit would allow me to run freebayes.

Good luck!

**Comment by SusanaFreitas** [comment]
yey, it works!
Sorry for not having tried it before, I wasnt sure how to add that option to my sbatch script. I tried it with srun and I didnt get the segfault (and my output started pilling up SNP calls).
I am still waiting to see if when I add the option on my sbatch script it works, but I cant see why it wouldnt...

Thanks again!!


```
#SBATCH options(...)

srun -p normal -t 2:00:00 --cpus-per-task=4 --mem=10GB --pty bash
ulimit -s 81920
freebayes -f 3_Tms_b3v08.fasta --bam-list trim3bam --min-mapping-quality 30 --min-coverage 5 --debug > Tms.trim3.fb.vcf
FB v1.3.1-19-g54bf409
```
