### ISSUE TITLE
VAF with DP or DPB

### ISSUE THREAD

**Issue by helloeoh001** [freebayes/freebayes#461]
Hello,

I use feebayes(v9.9.2-27-g5d5b8ac-dirty) to call SNPs and small INDELS.

To filter the calls, -F --min-alternate-fraction was set 0.05.

Then, it filtered out a few INDEL calls whose VAF would be more than 0.05 when using DP, but would be less than 0.05 when using DPB.

Does freebyes use 'DPB' to calculate VAF when filtering out?

If then, could you change it from 'DPB' to 'DP' ?

Or, could you give me the instruction how to change the corresponding source code?

Thank you!

**Comment by ekg** [comment]
freebayes is not filtering out the indel calls. It is not considering the
allele at all. -F is a minimum threshold as a fraction of the reads in one
individual. In other words we need at least 5% of the reads from one
individual to have the allele in order to consider it.

You would need to change the code to filter using DPB. I'm not sure this is
directly available where you'd need it in order to make the filtering be
based on that. DPB isn't well-defined relative to the -F filter, because
the -F filter will affect the haplotype scope that we're considering.

**Comment by helloeoh001** [comment]
Dr. ekg,

Thank you for quick reply.

My question was how to decide that the calls are supported by at least 5% reads.

There is no difference between DPB and DP when calling point mutations.

But, the coverage of 'deletion' calls are tricky.

DP is the coverage on the spot right 1 base ahead the 'deletion' position.

DPB is the average coverage of  overarching the positions of 'deletion' occurred

Often, DP is greater than DPB, because the coverage doesn't include the reads with deletion occurred.

Some of the deletion calls which  have more than 5% supporting reads (when using DP) were excluded. 

And I found that the deletion calls have less than 5% reads when using DPB.

So, my question is how to determine whether the calls have at least 5% reads?

Thank you!

**Comment by ekg** [comment]
Yes, this problem will occur because DP is defined based on the base before
and DPB is describing the whole haplotype call. However, -F does not do
what you want because it is defined _before_ the haplotype is determined,
so it won't always be the case that you can obtain DPB for the candidate
allele at the point when -F is implemented. You would actually have to do
quite a bit of coding to make this be the case.

Why do you need to filter things at 5% of the reads? Why don't you just
empirically determine an optimal QUAL threshold and go with that for
filtering? Or not filter at all, if you find it's not important for your
application?
