### ISSUE TITLE
.csi bam index support

### ISSUE THREAD

**Issue by jgarbe256** [freebayes/freebayes#491]
I'm calling variants in species with large genomes, some with chromosomes longer than the .bai BAM indexing format allows (2^29-1 or ~536Mbp). The .csi bam index format allows for longer chromosomes, and if Freebayes supported .csi then it could work with large genomes. The workaround is to modify the reference genome and split large genomes into smaller chunks, but that's not an ideal solution.

**Comment by lucventurini** [comment]
+1. This limitation prevents us from using freebayes on wheat (multiple chromosomes over the limit), unfortunately.

**Comment by ekg** [comment]
I thought seqLib gave us this superpower.

Can you use indexed cram? I haven't tested but assume it will work.

We should be able to run freebayes on wheat.

The numerous and comical bitwidth limits in BAM keep coming. Did 64 bit
integers ever hurt anyone?

**Comment by lucventurini** [comment]
@ekg 

My fault, the problem is that conda had installed a very old version (0.9.x).

The newer versions installed through Conda crash, probably because of some errors in linking. I am trying to recompile but it's giving me grief.

I will keep you updated, and thanks for answering.

**Comment by ekg** [comment]
Do you have root on the system? It's now in debian and guix.

**Comment by lucventurini** [comment]
@ekg 

I did manage to compile, in the end (it was a bit painful due to the Makefiles of bwa and other dependencies). 
I ended up discovering though that the problem was the fact that the regions BED file was BGZIP-compressed and indexed (as required by `strelka2`). Once I tried to use a decompressed file, `freebayes` functioned.

Please close the issue (`freebayes` does, indeed, work with CSI!). I might open another one re: support for BGZIP-compressed regions files.
