### ISSUE TITLE
can I resume the freebayes run which was killed by memory issue?

### ISSUE THREAD

**Issue by sckinta** [freebayes/freebayes#520]
I am using freebayes to call SNPs across whole human genome using 21 bam files.
```
freebayes-parallel \
<(fasta_generate_regions.py hg19.fa.fai 100000) 36 \
--max-complex-gap 75 \
-f hg19.fa \
-L bamlist.wg.txt \
> var1.vcf
```
It runs on 36 cores for 3 weeks and it was killed due to excessing requested memory (144G).  A large vcf file was generated but I am sure it is incomplete calling. Do you have an option for resume the freebayes call at the place it was killed? It takes forever to run this job if I re-start it.

**Comment by juanesarango** [comment]
@sckinta I created [toil_freebayes](https://github.com/papaemmelab/toil_freebayes) a wrapper tool around freebayes, that allows you to run freebayes using [toil](https://toil.readthedocs.io) to control parallel jobs in a better way. 

I even split jobs by regions that have a fixed number of reads, instead of fixed number of base pairs, to reduce the variance of runtime and memory usage across different regions. 

With toil, if one of the jobs fail for example caused by memory, you can resume your workflow by just passing a `--restart` flag.

Hope this is useful to you.
