### ISSUE TITLE
Error while running: coverage_to_regions.py 

### ISSUE THREAD

**Issue by foala** [freebayes/freebayes#609]
Hello,
I have been trying to run:
bamtools coverage -in aln.bam | coverage_to_regions.py ref.fasta 500 >ref.fasta.500.regions
freebayes-parallel ref.fasta.500.regions 36 -f ref.fasta aln.bam >out.vcf

but I keep getting this error:

> Traceback (most recent call last):
>   File "/vggpfs/fs3/vgl/scratch/vglshare/sandbox/fal/conda/envs/pg/bin/coverage_to_regions.py", line 16, in <module>
>     c, l = line.split("\t")[:2]
> ValueError: not enough values to unpack (expected 2, got 1)
> 

I generated the fai file again, but I still get the same error.
Please assist

**Comment by Nheyer** [comment]
@foala  can you post the first 10 lines or so of the output of  `bamtools coverage -in aln.bam`

**Comment by James-S-Santangelo** [comment]
I had the same issue and solved it by changing:

`coverage_to_regions.py ref.fasta 500` to `coverage_to_regions.py ref.fasta.fai 500` since coverage_to_regions.py required the reference FASTA index file as input and not the reference itself (see [here](https://github.com/ekg/freebayes/blob/master/scripts/coverage_to_regions.py)). 

I think there is a typo in the first line below from the `freebayes-parallel` documentation that that suggests using _ref.fa_ instead of _ref.fa.fai_ as input to `coverate_to_regions.py`.

https://github.com/ekg/freebayes/blob/2c1e395b9bf2565ae69fe61061eb28387f56637e/scripts/freebayes-parallel#L22-L23
