### ISSUE TITLE
Genotype call incorrect?

### ISSUE THREAD

**Issue by najoshi** [freebayes/freebayes#631]
So I ran freebayes 1.3.1 with all the default parameters on dog dna samples. I am getting this result for one of the samples (although it seems to be occurring in other samples too):

37	20134611	GCCGGGGTGCCGGGGGCC	GCCGGGGCC,GCGGGGGTGCCGGGGGCG,GCGGGGGCC,GCGGGGGTGCGGGGGGCG,GCGGGGGCG,GCCGGGGTGC	GT:DP:AD:RO:QR:AO:QA:GL	3/3:24:0,22,0,0,0,0,0:0:0:22,0,0,0,0,0:418,0,0,0,0,0:-50.6989,-42.8808,-10.0438,-81.5228,-45.9661,-5.53744,-73.8782,-38.3406,-12.4611,0,-81.5228,-45.9661,-12.4611,-12.4611,-5.53744,-81.5228,-45.9661,-12.4611,-12.4611,-12.4611,-5.53744,-73.8782,-38.3406,-76.9605,-69.3158,-76.9605,-76.9605,-47.6417

I'm only showing the relevant columns. So the genotype call is 3/3, which is NOT correct from looking at the alignment there:

![Screenshot_2020-07-07_22-45-50](https://user-images.githubusercontent.com/607905/86881659-a80f5200-c0a3-11ea-833e-dc18dcc87d3a.png)

This implies that most of the reads should go to the 1/1 genotype call. And, the AD field looks like this: 

0,22,0,0,0,0,0

There are 22 reads that contribute to the 1st alt allele and none to the others. So shouldn't the call be 1/1?

**Comment by najoshi** [comment]
Any help would be highly appreciated!

**Comment by Nheyer** [comment]
It looks like the GL flag is exactly zero for the 3/3 genotype, thus making it the highest likelyhood under the model so it called it that, but this might mean that there is some null equaling zero somewhere, can you please add a small reproducible sample so I can run it, it is possable the remapping freebayes dose is causing the decrepintsy, can you also include the full VCF line and the command you ran, because it may be the case that this is a low quality variant, that is, the Qual field is low, meaning that there is simmply not alot of support for any of the alleles, ( as 22 is really low ).
