### ISSUE TITLE
Maximum indel length when calling variants using PacBio HiFi (CCS) data

### ISSUE THREAD

**Issue by shelkmike** [freebayes/freebayes#722]
I'm using FreeBayes for HiFi reads mapped to a genome by Minimap2. Theoretically, very long indels (like, a kilobase or longer) can be called from such data. How does FreeBayes perform in regard to indel lengths? Does is have some maximum callable indel length?

**Comment by ekg** [comment]
There isn't a maximum length, but to call long indels you'll need multiple
observations of exactly the same haplotypes. That shouldn't be a problem
with deep HiFi data and ~1kb indels.

That said, Freebayes was designed for illumina data and shorter variants.
It may not work perfectly, and it may be slow for HiFi data. It's probably
nearing the end of it's useful life cycle due to these changes in
sequencing tech. I'd at least like to build a version that works on a
variation graph model (maybe built from an MSA) rather than the current
literal haplotype model.
