### ISSUE TITLE
very slow process

### ISSUE THREAD

**Issue by lmanchon** [freebayes/freebayes#766]
--Hi all,
 
i use freebayes v1.3.5 with this command and it takes 8h to process my bam file:

freebayes-parallel <(fasta_generate_regions.py GRCh38_p13.fa.fai 1000000) 24 -f GRCh38_p13.fa -t target.bed input.bam > output_freebayes.vcf

size of my bam is about ~ 780Mo

are there any parameters I can use to increase the speed ?

Thank you for your help .

**Comment by vinaydeep26** [comment]
I myself used this command. but you will notice that i used 72 threads instead of 24 you use. Also my Bam file was close to 300Gb and it took like 2 days for it to run. maybe try increasing the number of threads and decrease the size of blocks you're using (100,000) should be ideal.

freebayes-parallel <(fasta_generate_regions.py /references/genomes/MouseGenomesProject/onlyChromosomeC57_6J.fa.fai 100000) 72 -f /references/genomes/MouseGenomesProject/onlyChromosomeC57_6J.fa A_J_combined_with_DBA_2J_sorted_using_Picard_Tools_dedup_reads.bam > freebayes-parallel_A_J_combined_with_DBA_2J.vcf &
