### ISSUE TITLE
'Illegal instruction' error freebayes v1.3.7

### ISSUE THREAD

**Issue by nadjano** [freebayes/freebayes#776]
Hello, 
I try to run freebayes-1.3.7 installed with bioconda but there is immediately the error` Illegal instruction` raises.

I think this is the same issue as explained here:
https://github.com/pachterlab/kallisto/issues/399
https://github.com/bioconda/bioconda-recipes/issues/42633

Not sure if you can fix this or it's a bioconda problem.

freebayes-1.3.6 works fine for me.

**Comment by RealYHD** [comment]
Had a similar problem. Downgrading to 1.3.6 worked.

**Comment by travc** [comment]
Just a bump because I ran into the same problem just now with 1.3.7 (most recent version on bioconda).
It was working fine as part of a big pipeline... I updated, it broke.  I downgraded to 1.3.6 and it works fine again.
Hard to debug because it just immediately fails with "Illegal instruction" even when I strip it down to the only options being the reference and a bam-list.

**Comment by SwiftSeal** [comment]
Also experiencing this - freebayes 1.3.7 installed in a docker image https://hub.docker.com/r/swiftseal/drenseq which fails with illegal instruction. No obvious cause for what is triggering it - rerunning the exact same command with the container might have it fail only 50% of the time!
