### ISSUE TITLE
In/Del variants missed by Freebayes 1.3.8

### ISSUE THREAD

**Issue by h836472** [freebayes/freebayes#807]
Dear Freebayes Developers,

I am asking for your advice on a set of in/del variants that Freebayes seems to miss. When running FB 1.3.8 in debugging mode with -dd switch, one can see that these variants are always considered but finally removed with the log message: **no alternate genotype alleles passed filters at {genomic position}**. 

Apart from the allele frequency, that was already lowered, I could not find any obvious filtering rule that could be manually adjusted. Can you please tell me, what filters could be in effect that could eradicate approximately 60% of the proven pathogenic in/del variants in our panel sequencing? If needed, I can share you bam file extracts as well as debug log files for testing.

With kind regards,

Balazs Balint

**Comment by zkstewart** [comment]
I'm not a freebayes developer or contributor, but I thought I would reiterate here something I discovered some time ago in case anyone finds similar issues with freebayes not calling variants they would expect it to. I've commented on the issues https://github.com/freebayes/freebayes/issues/166 and https://github.com/freebayes/freebayes/issues/757 with part of my "solution" to this problem.

In short, and without trying to be inflammatory, _freebayes does not give reliable results_ which is especially true when using multiple samples as input. I had to devise a convoluted method of running freebayes to give results that _seemed_ okay. I strongly suspect there are some significant bugs hiding in the software and hence I've opted to use bcftools ever since I discovered this issue. I'd recommend that you use software which is actively maintained as freebayes does not seem to be getting anything other than basic maintenance.

**Comment by h836472** [comment]
Dear Zachary,

Thank you for your e-mail regarding the bug(s) in Freebayes. I appreciate
you stepping in with ideas and advices regarding the reported issue. There
is some follow-up data on our side too: Shortly after the bug report, I was
running a debugger Freebayes binary (specifically compiled for debugging)
and realized one interesting program behavior that seems to be directly
linked to all our in/del miss troubles. As it turns in/del Phred qualities
are often (mis)estimated as "0" even with insertions where (non-zero) Fastq
raw quality values are available. Such "zeroed" alleles never ever survive
the --*min*-*base*-quality=28 threshold that we normally use resulting in
undetected variants.

Disabling the filter (i.e. setting --*min*-*base*-quality=0) resolves this
issue. Right now, all in/dels that we missed before are included in the
outputs.
However, this tailoring comes with a serious side effect: by disabling the
base quality filter we get some 10-25% "new" variants, many of which will
be artifacts of all kinds. So, a subsequent careful variant filtering will
be essential to control the addition of false positive hits while
addressing previous false negative calls.

We have recently published a research tool of our own (completely unrelated
to FB) and I can also see how difficult tool maintenance is. Frankly, from
the "publish or perish" point of view, any bug fix, user support or tool
maintenance looks like wasted time. No grant money ever supports these
activities meaning that tool owners must perform these tasks on a totally
voluntary basis often "off-research times".

Having said that, it would be really nice to be able to use a quick-enough,
reliable-enough variant caller with a tiny bit of user support.

Balazs

**Comment by zkstewart** [comment]
That's interesting. Thanks for sharing your experiments with the software. It seems to support the idea that there are major bugs in the software which are causing issues with the output results.

And I fully agree with your perspective on the lack of merit or incentive for maintaining software. I absolutely did not mean for what I said to be a criticism of the authors themselves - they have produced an incredible bit of software, and their probable inability to realistically provide it the long term support it needs is no fault of their own. But, I do unfortunately believe that _people should not be using freebayes unless its issues are fixed_ since the program is providing flawed results with the user getting no indication that something has gone wrong.

**Comment by h836472** [comment]
I have seen many "interesting" bugs in commercial software too and the fact
that one subscribes to a paid tool / service does not guarantee proper user
support and rapid fix turnovers. I would not go as far as to advice against
Freebayes as it is well usable - with  adequate skepticism and pre-caution.
Same is true for Microsoft., I guess :).
Despite many old open issue tickets, we can consider Freebayes as active.
(last commit happened few months back)
Looking around, one realizes that there aren't many variant callers to
choose from. Plus, some of them are completely abandoned in terms of
support / development.
Take the examples from the benchmark article
https://doi.org/10.1186/s12864-022-08365-3
Clair3 active
DeepVariant active
Octopus  last commit > 1Y (!)
GATK active
FreeBayes active
Strelka2 abandoned: last commit >5T (!!!!!). This one was developed by
Illumina as a successor of the closed project Isaac. Here goes the theory
of abandoned tools being a consequence of academic rat-race for publication)
Sure, my next task will be a benchmark on all active tools within our
environment but there is a good chance that we keep using Freebayes with
disabled read base quality filter + a custom-made variant filtering.
