### ISSUE TITLE
std::out_of_range

### ISSUE THREAD

**Issue by przemekl** [freebayes/freebayes#89]
Freebayes version: v0.9.14-30-g6ac638c-dirty.
Example command line: freebayes -r chrEBV:0-171823 -f GCA_000001405.15_GRCh38_full_analysis_set.fna file.bam
Program exits with:
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr
Aborted (core dumped)

**Comment by llevar** [comment]
Hello,

I'm getting this error today on v0.9.21 running discovery mode against 1kgp data:

freebayes -f /reference/genome.fa.gz  /shared/data/samples/NA12878/NA12878.chrom11.ILLUMINA.bwa.CEU.low_coverage.20121211.bam  > /tmp/na12878_chrom11.vcf &

The crash is immediate.

Was the root cause of this issue every understood? What was the fix?

Thanks,

Sergei.
